export const INNOVATION_IDEA_START_TEXT = 'INNOVATION_IDEA_START'
export const INNOVATION_IDEA_END_TEXT = 'INNOVATION_IDEA_END'
export const INNOVATION_IDEA_SUBMITTED_TEXT = 'INNOVATION_IDEA_SUBMITTED'

export const RECOMMENDATION_START_TEXT = 'RECOMMENDATION_START'
export const RECOMMENDATION_END_TEXT = 'RECOMMENDATION_END'
