export const ApiEndpoints = {
  MAGIC_LOGIN_LINK_REQUEST: '/v1.0/m-link/',
  MAGIC_LOGIN: '/v1.0/m-link/login/',
  REFRESH_TOKEN: '/v1.0/auth/refresh_token/',
  GET_ACCOUNT_INFO: '/v1.0/auth/employee/',
  SET_PREFERRED_LANG: '/v1.0/preferred-lang/',
  GET_MANAGER_REPORTS: '/v1.0/manager/:employeeId/reports/',
  GET_REPORT_GOALS: '/v1.0/reports/:reportId/goals/',
  GET_REPORT_INNOVATION_IDEAS: '/v1.0/report/:reportId/ideas/',
  GET_REPORT_INNOVATION_IDEAS_MATRIX: '/v1.0/report/:reportId/ideas-matrix/',
  GET_REPORT_KPI_SCORES: '/v1.0/report/:reportId/kpis/',
  GET_REPORT_EXECUTIVE_SUMMARY: '/v1.0/reports/:reportId/executive_summary/',
  GET_INNOVATION_IDEA: '/v1.0/innovation-ideas/:id/',
  RATE_INNOVATION_IDEA: '/v1.0/ideas/:id/rate/',
  CREATE_NEW_GOAL_FOR_REPORT: '/v1.0/reports/:reportId/goals/',
  GET_MODULES: '/v1.0/modules/',
  GET_MODULE_URLS: '/v1.0/modules/urls/',
  GET_CONTENT_SUMMARIES: '/v1.0/modules/:id/content-summaries/',
  UPSERT_MODULE_SCHEDULE: '/v1.0/modules/:id/schedules/',
  GET_MODULE_SCHEDULES: '/v1.0/module-schedules/',
  GET_DEEP_DIVES: '/v1.0/deep_dives/',
  GET_DEEP_DIVE_OAO_CONTENTS: '/v1.0/deep_dives/:deepDiveId/oao_content/',
  GET_DEEP_DIVE_LIBRARIES: '/v1.0/deep_dives/:deepDiveId/libraries/',
  GET_DEEP_DIVE_LIBRARY_CONTENTS: '/v1.0/libraries/:libraryId/content/',
  GET_OAO_CONTENT_OUTCOMES: '/v1.0/oao_content/:oaoContentId/outcomes/',
  GET_VIEWED_OAO_CONTENTS: '/v1.0/oao_content/views/',
  VIEW_OAO_CONTENT: '/v1.0/oao_content/:id/views/',
  CREATE_INNOVATION_IDEA: '/v1.0/participants/:participationId/ideas/',
  GET_PARTICIPANT_INNOVATION_IDEA: '/v1.0/employee/idea/',
} as const

export const LlmApiEndpoints = {
  SEND_MESSAGE: '/api/v1/chat/',
  CREATE_CUSTOM_CHAT: '/api/v1/chat/custom/',
  GET_INNOVATION_IDEAS: '/api/v1/ideas/',
  CREATE_INNOVATION_IDEA: '/api/v1/ideas/',
  DISTINCT_INNOVATION_IDEA_CHAT_SEND_MESSAGE: '/api/v1/idea/chat/',
} as const
